strategies:
  bb_rsi_adx:
    allocation: 1.0
    enabled: true
    indicators:
      adx:
        period: 14
        threshold: 25
      bollinger_bands:
        period: 20
        std_dev: 2.0
      rsi:
        overbought: 75
        oversold: 25
        period: 14
    max_positions: 3
    position_size: 100.0
    stop_loss: 2.0
    take_profit: 4.0
    timeframe: 15m
  hull_suite:
    allocation: 1.0
    enabled: true
    indicators:
      atr:
        multiplier: 2.0
        period: 14
      hull_ma:
        period: 34
        source: close
    max_positions: 3
    position_size: 100.0
    stop_loss: 2.0
    take_profit: 4.0
    timeframe: 15m
test:
  key: test_value
test_key: test_value
trading:
  active_strategies: []
  default_order_size: 100.0
  log_level: INFO
  log_performance: true
  log_trades: true
  max_daily_loss: 500.0
  max_drawdown: 10.0
  max_leverage: 10
  max_position_size: 1000.0
  min_profit_threshold: 0.5
  rate_limit_requests_per_second: 10.0
  slippage_tolerance: 0.1
  stop_loss_percentage: 2.0
  strategy_allocation:
    bb_rsi_adx: 0.6
    hull_suite: 0.4
  take_profit_percentage: 4.0
  testnet: true
  wallet_address: '0x306D29F56EA1345c7E6F1ff27657ba05cEE15D4F'
  websocket_reconnect_attempts: 5
